### PR TITLE
added ability to remove a JSON prefix if sent

### PR DESCRIPTION
**Pull request by arkarkark**
this is a fix for issue21 I filed a couple of days ago.

https://github.com/gildas-lormeau/JSONView-for-Chrome/issues/21

### CODE REVIEW

**Comment by AncientSwordRage** [comment]
In the mean time, could you explain/point to how to integrate this with a local version?

**Comment by arkarkark** [comment]
@AncientSwordRage it seems to be taking forever for the chrome store to approve publishing my patched version of this extension. So you can do it locally.

# check out my version into a directory on your machine
git clone git@github.com:arkarkark/JSONView-for-Chrome.git

in chrome open tools->extensions turn on developer mode (top right) and then click the `load unpacked extension` choose the JSONView-for-Chrome directory

and you should be good to go.

make sure to turn off the installed version you already have.

**Comment by AncientSwordRage** [comment]
@arkarkark I'm getting `Could not load manifest.` when I try that, do I need to make what I cloned?

**Comment by arkarkark** [comment]
then try the WebContent directory (which has a manifest.json file in it)

**Comment by AncientSwordRage** [comment]
@arkarkark yeah that works!

**Comment by gildas-lormeau** [comment]
Thank you, I added an option called "Regular expression for removing JSON prefix". It will be available in the version 0.1.14.

**Pull request closed without merging**
